{ pkgs, inputs }:
[
    inputs.isd.packages.${pkgs.system}.default
    pkgs.htop
    pkgs.fzf
    pkgs.ripgrep
    pkgs.fd
    pkgs.tuc
    pkgs.tealdeer
    pkgs.eza
    pkgs.bat
    pkgs.prettyping
    pkgs.ncdu
    pkgs.direnv
    pkgs.autojump
    pkgs.atuin
    pkgs.gitflow
    pkgs.traceroute
    pkgs.neovim
    pkgs.putty
    pkgs.mtr
    pkgs.shellcheck
    pkgs.restic
    pkgs.tree
    pkgs.lnav
    pkgs.uv
    pkgs.fuzzel
    pkgs.ranger
    pkgs.xfce.thunar
    pkgs.copyq
]
