{ pkgs, inputs }:
[
    inputs.isd.packages.${pkgs.system}.default
    pkgs.htop
    pkgs.fzf
    pkgs.ripgrep
    pkgs.fd
    pkgs.tuc
    pkgs.eza
    pkgs.bat
    pkgs.prettyping
    pkgs.ncdu
    pkgs.autojump
    pkgs.atuin
    pkgs.traceroute
    pkgs.putty
    pkgs.mtr
    pkgs.restic
    pkgs.tree
    pkgs.lnav
    pkgs.fuzzel
    pkgs.ranger
    pkgs.xfce.thunar
    pkgs.copyq
    pkgs.betterdiscordctl
    pkgs.kdePackages.kate
    pkgs.thefuck
    pkgs.httpie
    pkgs.brightnessctl
    pkgs.networkmanagerapplet
    pkgs.standardnotes
    pkgs.thunderbird
    pkgs.bitwarden-desktop
    pkgs.libreoffice-fresh
    pkgs.obsidian
    pkgs.logseq
    pkgs.discord
    pkgs.jq
    pkgs.wireguard-tools
    pkgs.evince
]
